In [1]:
# Install (run once)
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\hp\anaconda3\lib\site-packages (9.6.0)

In [2]:
import requests
import pandas as pd
import mysql.connector

In [3]:
API_KEY = "b3d7f61023msh362a5491e103391p1f5aecjsnb0cb3e72401e" 

HEADERS = {
    "X-RapidAPI-Key": API_KEY,
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

In [4]:
def get_live_matches():
    url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"
    
    response = requests.get(url, headers=HEADERS)
    data = response.json()
    
    return data

In [5]:
data = get_live_matches()
print(data)

{'typeMatches': [{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 12081, 'seriesName': 'United Arab Emirates tour of Nepal 2026', 'matches': [{'matchInfo': {'matchId': 153803, 'seriesId': 12081, 'seriesName': 'United Arab Emirates tour of Nepal 2026', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1776770100000', 'endDate': '1776782700000', 'state': 'Complete', 'status': 'Nepal won by 8 wkts', 'team1': {'teamId': 7, 'teamName': 'United Arab Emirates', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 72, 'teamName': 'Nepal', 'teamSName': 'NEP', 'imageId': 776331}, 'venueInfo': {'id': 458, 'ground': 'Tribhuvan University International Cricket Ground', 'city': 'Kirtipur', 'timezone': '+05:45', 'latitude': '27.6768145', 'longitude': '85.287199'}, 'currBatTeamId': 72, 'seriesStartDt': '1776643200000', 'seriesEndDt': '1776902400000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 128, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 129, 'wickets': 2, 'overs': 15.5}}}}]}}]}, {'matchType': 'League', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 9241, 'seriesName': 'Indian Premier League 2026', 'matches': [{'matchInfo': {'matchId': 151856, 'seriesId': 9241, 'seriesName': 'Indian Premier League 2026', 'matchDesc': '31st Match', 'matchFormat': 'T20', 'startDate': '1776780000000', 'endDate': '1776792600000', 'state': 'In Progress', 'status': 'Delhi Capitals opt to bowl', 'team1': {'teamId': 255, 'teamName': 'Sunrisers Hyderabad', 'teamSName': 'SRH', 'imageId': 860066}, 'team2': {'teamId': 61, 'teamName': 'Delhi Capitals', 'teamSName': 'DC', 'imageId': 860040}, 'venueInfo': {'id': 80, 'ground': 'Rajiv Gandhi International Stadium', 'city': 'Hyderabad', 'timezone': '+05:30', 'latitude': '17.406495', 'longitude': '78.550451'}, 'currBatTeamId': 255, 'seriesStartDt': '1774656000000', 'seriesEndDt': '1780358400000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 152, 'wickets': 1, 'overs': 13.1}}}}]}}, {'seriesAdWrapper': {'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matches': [{'matchInfo': {'matchId': 149260, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '31st Match', 'matchFormat': 'T20', 'startDate': '1776780000000', 'endDate': '1776792600000', 'state': 'In Progress', 'status': 'Rawalpindiz opt to bat', 'team1': {'teamId': 3116, 'teamName': 'Rawalpindiz', 'teamSName': 'RWP', 'imageId': 883174}, 'team2': {'teamId': 437, 'teamName': 'Multan Sultans', 'teamSName': 'MS', 'imageId': 883178}, 'venueInfo': {'id': 24, 'ground': 'National Stadium', 'city': 'Karachi', 'timezone': '+05:00', 'latitude': '24.892373', 'longitude': '67.086411'}, 'currBatTeamId': 3116, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'In Progress', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 103, 'wickets': 3, 'overs': 14.4}}}}, {'matchInfo': {'matchId': 149249, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '30th Match', 'matchFormat': 'T20', 'startDate': '1776763800000', 'endDate': '1776776400000', 'state': 'Complete', 'status': 'Lahore Qalandars won by 9 runs', 'team1': {'teamId': 333, 'teamName': 'Lahore Qalandars', 'teamSName': 'LHQ', 'imageId': 883181}, 'team2': {'teamId': 331, 'teamName': 'Quetta Gladiators', 'teamSName': 'QTG', 'imageId': 883182}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 333, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'Complete', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 197, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 188, 'wickets': 7, 'overs': 19.6}}}}]}}]}, {'matchType': 'Women', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 12015, 'seriesName': 'ICC Womens T20I Challenge Trophy 2026', 'matches': [{'matchInfo': {'matchId': 153439, 'seriesId': 12015, 'seriesName': 'ICC Womens T20I Challenge Trophy 2026', 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1776769200000', 'endDate': '1776781800000', 'state': 'Complete', 'status': 'Italy Women won by 4 wkts', 'team1': {'teamId': 506, 'teamName': 'Vanuatu Women', 'teamSName': 'VANW', 'imageId': 776231}, 'team2': {'teamId': 1125, 'teamName': 'Italy Women', 'teamSName': 'ITAW', 'imageId': 776298}, 'venueInfo': {'id': 818, 'ground': 'Gahanga International Cricket Stadium', 'city': 'Kigali City', 'timezone': '+02:00', 'latitude': '-1.950851', 'longitude': '30.061507'}, 'currBatTeamId': 1125, 'seriesStartDt': '1776470400000', 'seriesEndDt': '1777766400000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 114, 'wickets': 6, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 115, 'wickets': 6, 'overs': 19.3}}}}, {'matchInfo': {'matchId': 153428, 'seriesId': 12015, 'seriesName': 'ICC Womens T20I Challenge Trophy 2026', 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1776754800000', 'endDate': '1776767400000', 'state': 'Complete', 'status': 'Rwanda Women won by 1 run', 'team1': {'teamId': 720, 'teamName': 'Rwanda Women', 'teamSName': 'RWAW', 'imageId': 248448}, 'team2': {'teamId': 592, 'teamName': 'United States of America Women', 'teamSName': 'USAW', 'imageId': 776222}, 'venueInfo': {'id': 818, 'ground': 'Gahanga International Cricket Stadium', 'city': 'Kigali City', 'timezone': '+02:00', 'latitude': '-1.950851', 'longitude': '30.061507'}, 'currBatTeamId': 720, 'seriesStartDt': '1776470400000', 'seriesEndDt': '1777766400000', 'isTimeAnnounced': True, 'stateTitle': 'RWAW Won'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 127, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 126, 'wickets': 5, 'overs': 19.6}}}}]}}]}], 'filters': {'matchType': ['International', 'League', 'Domestic', 'Women']}, 'appIndex': {'seoTitle': 'Live Cricket Score - Scorecard and Match Results', 'webURL': 'www.cricbuzz.com/live-cricket-scores/'}, 'responseLastUpdated': '1776783957'}

In [6]:
def extract_matches(data):
    matches = []

    for type_match in data.get("typeMatches", []):
        for series in type_match.get("seriesMatches", []):
            wrapper = series.get("seriesAdWrapper", {})

            for match in wrapper.get("matches", []):
                info = match.get("matchInfo", {})
                score = match.get("matchScore", {})

                matches.append({
                    # 🔑 Primary Key
                    "match_id": info.get("matchId"),

                    # 📊 Series Info
                    "series_id": info.get("seriesId"),
                    "series_name": info.get("seriesName"),

                    # 🏏 Match Info
                    "match_desc": info.get("matchDesc"),
                    "match_format": info.get("matchFormat"),
                    "status": info.get("status"),

                    # 👥 Teams
                    "team1": info.get("team1", {}).get("teamName"),
                    "team2": info.get("team2", {}).get("teamName"),

                    # 📍 Venue
                    "venue": info.get("venueInfo", {}).get("ground"),
                    "city": info.get("venueInfo", {}).get("city"),

                    # 🕒 Dates (converted from timestamp → readable)
                    "start_date": info.get("startDate"),
                    "end_date": info.get("endDate"),

                    # ⚡ Optional Score Summary (safe extraction)
                    "team1_runs": score.get("team1Score", {}).get("inngs1", {}).get("runs"),
                    "team2_runs": score.get("team2Score", {}).get("inngs1", {}).get("runs")
                })

    return matches

In [7]:
matches = extract_matches(data)
df = pd.DataFrame(matches)
df

,match_id,series_id,series_name,match_desc,match_format,status,team1,team2,venue,city,start_date,end_date,team1_runs,team2_runs
0,153803,12081,United Arab Emirates tour of Nepal 2026,2nd T20I,T20,Nepal won by 8 wkts,United Arab Emirates,Nepal,Tribhuvan University International Cricket Ground,Kirtipur,1776770100000,1776782700000,128,129.0
1,151856,9241,Indian Premier League 2026,31st Match,T20,Delhi Capitals opt to bowl,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,1776780000000,1776792600000,152,NaN
2,149260,11537,Pakistan Super League 2026,31st Match,T20,Rawalpindiz opt to bat,Rawalpindiz,Multan Sultans,National Stadium,Karachi,1776780000000,1776792600000,103,NaN
3,149249,11537,Pakistan Super League 2026,30th Match,T20,Lahore Qalandars won by 9 runs,Lahore Qalandars,Quetta Gladiators,Gaddafi Stadium,Lahore,1776763800000,1776776400000,197,188.0
4,153439,12015,ICC Womens T20I Challenge Trophy 2026,6th Match,T20,Italy Women won by 4 wkts,Vanuatu Women,Italy Women,Gahanga International Cricket Stadium,Kigali City,1776769200000,1776781800000,114,115.0
5,153428,12015,ICC Womens T20I Challenge Trophy 2026,5th Match,T20,Rwanda Women won by 1 run,Rwanda Women,United States of America Women,Gahanga International Cricket Stadium,Kigali City,1776754800000,1776767400000,127,126.0

In [27]:
df.columns

Index(['match_id', 'series_id', 'series_name', 'match_desc', 'match_format',
       'status', 'team1', 'team2', 'venue', 'city', 'start_date', 'end_date',
       'team1_runs', 'team2_runs'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   match_id      6 non-null      int64
 1   series_id     6 non-null      int64
 2   series_name   6 non-null      object
 3   match_desc    6 non-null      object
 4   match_format  6 non-null      object
 5   status        6 non-null      object
 6   team1         6 non-null      object
 7   team2         6 non-null      object
 8   venue         6 non-null      object
 9   city          6 non-null      object
 10  start_date    6 non-null      object
 11  end_date      6 non-null      object
 12  team1_runs    6 non-null      int64
 13  team2_runs    4 non-null      float64
dtypes: float64(1), int64(3), object(10)
memory usage: 804.0+ bytes

In [9]:
df["start_date"] = pd.to_datetime(df["start_date"], unit='ms')
df["end_date"] = pd.to_datetime(df["end_date"], unit='ms')

C:\Users\hp\AppData\Local\Temp\ipykernel_20536\892971224.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df["start_date"] = pd.to_datetime(df["start_date"], unit='ms')
C:\Users\hp\AppData\Local\Temp\ipykernel_20536\892971224.py:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df["end_date"] = pd.to_datetime(df["end_date"], unit='ms')

In [10]:
df = df.fillna({
    "team2_runs": 0
})

In [11]:
df.head()

,match_id,series_id,series_name,match_desc,match_format,status,team1,team2,venue,city,start_date,end_date,team1_runs,team2_runs
0,153803,12081,United Arab Emirates tour of Nepal 2026,2nd T20I,T20,Nepal won by 8 wkts,United Arab Emirates,Nepal,Tribhuvan University International Cricket Ground,Kirtipur,2026-04-21 11:15:00,2026-04-21 14:45:00,128,129.0
1,151856,9241,Indian Premier League 2026,31st Match,T20,Delhi Capitals opt to bowl,Sunrisers Hyderabad,Delhi Capitals,Rajiv Gandhi International Stadium,Hyderabad,2026-04-21 14:00:00,2026-04-21 17:30:00,152,0.0
2,149260,11537,Pakistan Super League 2026,31st Match,T20,Rawalpindiz opt to bat,Rawalpindiz,Multan Sultans,National Stadium,Karachi,2026-04-21 14:00:00,2026-04-21 17:30:00,103,0.0
3,149249,11537,Pakistan Super League 2026,30th Match,T20,Lahore Qalandars won by 9 runs,Lahore Qalandars,Quetta Gladiators,Gaddafi Stadium,Lahore,2026-04-21 09:30:00,2026-04-21 13:00:00,197,188.0
4,153439,12015,ICC Womens T20I Challenge Trophy 2026,6th Match,T20,Italy Women won by 4 wkts,Vanuatu Women,Italy Women,Gahanga International Cricket Stadium,Kigali City,2026-04-21 11:00:00,2026-04-21 14:30:00,114,115.0

In [12]:
def get_scorecard(match_id):
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_id}/hscard"
    
    response = requests.get(url, headers=HEADERS)
    return response.json()

In [13]:
scorecard = get_scorecard(df['match_id'][0])
print(scorecard)

{'scorecard': [{'inningsid': 1, 'batsman': [{'id': 18987, 'balls': 1, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Muhammad Waseem', 'nickname': 'Muhammad Waseem', 'iscaptain': True, 'iskeeper': False, 'outdec': 'lbw b Hemant Dhami', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 14999, 'balls': 22, 'runs': 30, 'fours': 2, 'sixes': 2, 'strkrate': '136.36', 'name': 'Adeeb Usmani', 'nickname': 'Adeeb Usmani', 'iscaptain': False, 'iskeeper': True, 'outdec': 'lbw b Sandeep Lamichhane', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 14227, 'balls': 4, 'runs': 1, 'fours': 0, 'sixes': 0, 'strkrate': '25', 'name': 'Alishan Sharafu', 'nickname': 'Alishan Sharafu', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Lokesh Bam b Nandan Yadav', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 6322, 'balls': 3, 'runs': 1, 'fours': 0, 'sixes': 0, 'strkrate': '33.33', 'name': 'Harpreet Singh Bhatia', 'nickname': 'Harpreet Singh', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Hemant Dhami', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8351, 'balls': 42, 'runs': 53, 'fours': 3, 'sixes': 4, 'strkrate': '126.19', 'name': 'Akshdeep Nath', 'nickname': 'Akshdeep Nath', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1464054, 'balls': 5, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Sohaib Khan', 'nickname': 'Sohaib Khan', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Hemant Dhami b Shahab Alam', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22841, 'balls': 2, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Nilansh Keswani', 'nickname': 'Nilansh Keswani', 'iscaptain': False, 'iskeeper': False, 'outdec': 'run out (Dipendra Singh Airee/Lokesh Bam)', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 1448301, 'balls': 36, 'runs': 32, 'fours': 2, 'sixes': 1, 'strkrate': '88.89', 'name': 'Muhammad Arfan', 'nickname': 'Muhammad Arfan', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Dipendra Singh Airee b Sandeep Lamichhane', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1447465, 'balls': 1, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Khuzaima Tanveer', 'nickname': 'Khuzaima Tanveer', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Dipendra Singh Airee b Sandeep Lamichhane', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 51658, 'balls': 5, 'runs': 8, 'fours': 1, 'sixes': 0, 'strkrate': '160', 'name': 'Muhammad Zuhaib', 'nickname': 'Muhammad Zuhaib', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1463374, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Ajay Kumar', 'nickname': 'Ajay Kumar', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}], 'bowler': [{'id': 52579, 'overs': '4', 'maidens': 0, 'wickets': 2, 'runs': 20, 'economy': '5', 'name': 'Hemant Dhami', 'nickname': 'Hemant Dhami', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 40, 'rpb': 0.5, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12113, 'overs': '4', 'maidens': 0, 'wickets': 1, 'runs': 44, 'economy': '11', 'name': 'Nandan Yadav', 'nickname': 'Nandan Yadav', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 40, 'rpb': 1.1, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 13222, 'overs': '3', 'maidens': 0, 'wickets': 1, 'runs': 29, 'economy': '9.7', 'name': 'Shahab Alam', 'nickname': 'Shahab Alam', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 30, 'rpb': 0.97, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 11158, 'overs': '4', 'maidens': 1, 'wickets': 3, 'runs': 6, 'economy': '1.5', 'name': 'Sandeep Lamichhane', 'nickname': 'Sandeep Lamichhane', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 1, 'balls': 40, 'rpb': 0.15, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11155, 'overs': '3', 'maidens': 0, 'wickets': 0, 'runs': 16, 'economy': '5.3', 'name': 'Dipendra Singh Airee', 'nickname': 'Dipendra Singh Airee', 'iscaptain': True, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 30, 'rpb': 0.53, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1448017, 'overs': '1', 'maidens': 0, 'wickets': 0, 'runs': 11, 'economy': '11', 'name': 'Santosh Yadav', 'nickname': 'Santosh Yadav', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 10, 'rpb': 1.1, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 20146, 'overs': '1', 'maidens': 0, 'wickets': 0, 'runs': 1, 'economy': '1', 'name': 'Gulsan Jha', 'nickname': 'Gulsan Jha', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 10, 'rpb': 0.1, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 18987, 'batsmanname': 'Muhammad Waseem', 'overnbr': 0.1, 'runs': 0, 'ballnbr': 1}, {'batsmanid': 14227, 'batsmanname': 'Alishan Sharafu', 'overnbr': 1.4, 'runs': 15, 'ballnbr': 10}, {'batsmanid': 6322, 'batsmanname': 'Harpreet Singh Bhatia', 'overnbr': 2.2, 'runs': 20, 'ballnbr': 14}, {'batsmanid': 14999, 'batsmanname': 'Adeeb Usmani', 'overnbr': 6.3, 'runs': 47, 'ballnbr': 39}, {'batsmanid': 1464054, 'batsmanname': 'Sohaib Khan', 'overnbr': 7.3, 'runs': 48, 'ballnbr': 45}, {'batsmanid': 22841, 'batsmanname': 'Nilansh Keswani', 'overnbr': 7.5, 'runs': 48, 'ballnbr': 47}, {'batsmanid': 1448301, 'batsmanname': 'Muhammad Arfan', 'overnbr': 18.2, 'runs': 112, 'ballnbr': 110}, {'batsmanid': 1447465, 'batsmanname': 'Khuzaima Tanveer', 'overnbr': 18.3, 'runs': 112, 'ballnbr': 111}]}, 'extras': {'legbyes': 0, 'byes': 1, 'wides': 1, 'noballs': 1, 'penalty': 0, 'total': 3}, 'score': 128, 'wickets': 8, 'overs': 20.0, 'runrate': 6.4, 'batteamname': 'United Arab Emirates', 'batteamsname': 'UAE', 'isdeclared': False, 'isfollowon': False, 'ballnbr': 120, 'rpb': 1.07, 'partnership': {'partnership': [{'id': 0, 'bat1id': 18987, 'bat1name': 'Muhammad Waseem', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 14999, 'bat2name': 'Adeeb Usmani', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 0, 'totalballs': 1, 'bat1balls': 1, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 14227, 'bat1name': 'Alishan Sharafu', 'bat1runs': 1, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 14999, 'bat2name': 'Adeeb Usmani', 'bat2runs': 14, 'bat2fours': 0, 'bat2sixes': 2, 'totalruns': 15, 'totalballs': 9, 'bat1balls': 4, 'bat2balls': 5, 'teamname': '', 'teamid': 0, 'bat1ones': 1, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 2, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 2}, {'id': 0, 'bat1id': 6322, 'bat1name': 'Harpreet Singh', 'bat1runs': 1, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 14999, 'bat2name': 'Adeeb Usmani', 'bat2runs': 4, 'bat2fours': 1, 'bat2sixes': 0, 'totalruns': 5, 'totalballs': 4, 'bat1balls': 3, 'bat2balls': 1, 'teamname': '', 'teamid': 0, 'bat1ones': 1, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 1, 'bat2sixers': 0}, {'id': 0, 'bat1id': 8351, 'bat1name': 'Akshdeep Nath', 'bat1runs': 15, 'bat1fours': 0, 'bat1sixes': 2, 'bat2id': 14999, 'bat2name': 'Adeeb Usmani', 'bat2runs': 12, 'bat2fours': 1, 'bat2sixes': 0, 'totalruns': 27, 'totalballs': 25, 'bat1balls': 9, 'bat2balls': 16, 'teamname': '', 'teamid': 0, 'bat1ones': 3, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 2, 'bat2ones': 4, 'bat2twos': 2, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 1, 'bat2sixers': 0}, {'id': 0, 'bat1id': 8351, 'bat1name': 'Akshdeep Nath', 'bat1runs': 1, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 1464054, 'bat2name': 'Sohaib Khan', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 1, 'totalballs': 6, 'bat1balls': 1, 'bat2balls': 5, 'teamname': '', 'teamid': 0, 'bat1ones': 1, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 8351, 'bat1name': 'Akshdeep Nath', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 22841, 'bat2name': 'Nilansh Keswani', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 0, 'totalballs': 2, 'bat1balls': 0, 'bat2balls': 2, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 8351, 'bat1name': 'Akshdeep Nath', 'bat1runs': 30, 'bat1fours': 3, 'bat1sixes': 1, 'bat2id': 1448301, 'bat2name': 'Muhammad Arfan', 'bat2runs': 32, 'bat2fours': 2, 'bat2sixes': 1, 'totalruns': 64, 'totalballs': 63, 'bat1balls': 27, 'bat2balls': 36, 'teamname': '', 'teamid': 0, 'bat1ones': 12, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 3, 'bat1sixers': 1, 'bat2ones': 12, 'bat2twos': 3, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 2, 'bat2sixers': 1}, {'id': 0, 'bat1id': 8351, 'bat1name': 'Akshdeep Nath', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 1447465, 'bat2name': 'Khuzaima Tanveer', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 0, 'totalballs': 1, 'bat1balls': 0, 'bat2balls': 1, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 8351, 'bat1name': 'Akshdeep Nath', 'bat1runs': 7, 'bat1fours': 0, 'bat1sixes': 1, 'bat2id': 51658, 'bat2name': 'Muhammad Zuhaib', 'bat2runs': 8, 'bat2fours': 1, 'bat2sixes': 0, 'totalruns': 16, 'totalballs': 9, 'bat1balls': 5, 'bat2balls': 5, 'teamname': '', 'teamid': 0, 'bat1ones': 1, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 1, 'bat2ones': 2, 'bat2twos': 1, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 1, 'bat2sixers': 0}]}}, {'inningsid': 2, 'batsman': [{'id': 11290, 'balls': 57, 'runs': 84, 'fours': 12, 'sixes': 2, 'strkrate': '147.37', 'name': 'Kushal Bhurtel', 'nickname': 'Kushal Bhurtel', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 15400, 'balls': 17, 'runs': 19, 'fours': 1, 'sixes': 2, 'strkrate': '111.76', 'name': 'Kushal Malla', 'nickname': 'Kushal Malla', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Muhammad Waseem b Muhammad Arfan', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1448017, 'balls': 4, 'runs': 1, 'fours': 0, 'sixes': 0, 'strkrate': '25', 'name': 'Santosh Yadav', 'nickname': 'Santosh Yadav', 'iscaptain': False, 'iskeeper': False, 'outdec': 'run out (Adeeb Usmani)', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 11155, 'balls': 17, 'runs': 23, 'fours': 3, 'sixes': 0, 'strkrate': '135.29', 'name': 'Dipendra Singh Airee', 'nickname': 'Dipendra Singh Airee', 'iscaptain': True, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 15397, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Lokesh Bam', 'nickname': 'Lokesh Bam', 'iscaptain': False, 'iskeeper': True, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 10126, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Aarif Sheikh', 'nickname': 'Aarif Sheikh', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 20146, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Gulsan Jha', 'nickname': 'Gulsan Jha', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 12113, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Nandan Yadav', 'nickname': 'Nandan Yadav', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11158, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Sandeep Lamichhane', 'nickname': 'Sandeep Lamichhane', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 13222, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Shahab Alam', 'nickname': 'Shahab Alam', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 52579, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Hemant Dhami', 'nickname': 'Hemant Dhami', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 1463374, 'overs': '4', 'maidens': 1, 'wickets': 0, 'runs': 16, 'economy': '4', 'name': 'Ajay Kumar', 'nickname': 'Ajay Kumar', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 1, 'balls': 40, 'rpb': 0.4, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 1447465, 'overs': '3', 'maidens': 0, 'wickets': 0, 'runs': 39, 'economy': '13', 'name': 'Khuzaima Tanveer', 'nickname': 'Khuzaima Tanveer', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 30, 'rpb': 1.3, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 22841, 'overs': '3.5', 'maidens': 0, 'wickets': 0, 'runs': 31, 'economy': '8.1', 'name': 'Nilansh Keswani', 'nickname': 'Nilansh Keswani', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 35, 'rpb': 0.89, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': 'IN'}, {'id': 1448301, 'overs': '3', 'maidens': 0, 'wickets': 1, 'runs': 19, 'economy': '6.3', 'name': 'Muhammad Arfan', 'nickname': 'Muhammad Arfan', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 30, 'rpb': 0.63, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 51658, 'overs': '2', 'maidens': 0, 'wickets': 0, 'runs': 24, 'economy': '12', 'name': 'Muhammad Zuhaib', 'nickname': 'Muhammad Zuhaib', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 20, 'rpb': 1.2, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 15400, 'batsmanname': 'Kushal Malla', 'overnbr': 7.3, 'runs': 67, 'ballnbr': 45}, {'batsmanid': 1448017, 'batsmanname': 'Santosh Yadav', 'overnbr': 8.3, 'runs': 71, 'ballnbr': 51}]}, 'extras': {'legbyes': 0, 'byes': 0, 'wides': 2, 'noballs': 0, 'penalty': 0, 'total': 2}, 'score': 129, 'wickets': 2, 'overs': 15.5, 'r

In [14]:
def extract_players(scorecard, match_id):
    players = []

    for innings in scorecard.get("scorecard", []):
        innings_id = innings.get("inningsid")
        batsmen = innings.get("batsman", [])

        for b in batsmen:
            players.append({
                "player_id": b.get("id"),
                "match_id": match_id,
                "innings_id": innings_id,

                "name": b.get("name"),
                "runs": b.get("runs", 0),
                "balls": b.get("balls", 0),
                "fours": b.get("fours", 0),
                "sixes": b.get("sixes", 0),

                # convert strike rate safely (string → float)
                "strike_rate": float(b.get("strkrate", 0)) if b.get("strkrate") else 0.0,

                # handle empty dismissal
                "out_desc": b.get("outdec") if b.get("outdec") else "not out"
            })

    return players

In [15]:
players = extract_players(scorecard, match_id=142142)

import pandas as pd
df_players = pd.DataFrame(players)

print(df_players.head())

   player_id  match_id  innings_id                   name  runs  balls  fours  \
0      18987    142142           1        Muhammad Waseem     0      1      0
1      14999    142142           1           Adeeb Usmani    30     22      2
2      14227    142142           1        Alishan Sharafu     1      4      0
3       6322    142142           1  Harpreet Singh Bhatia     1      3      0
4       8351    142142           1          Akshdeep Nath    53     42      3

   sixes  strike_rate                     out_desc
0      0         0.00           lbw b Hemant Dhami
1      2       136.36     lbw b Sandeep Lamichhane
2      0        25.00  c Lokesh Bam b Nandan Yadav
3      0        33.33           lbw b Hemant Dhami
4      4       126.19                      not out

In [28]:
df_players.columns

Index(['player_id', 'match_id', 'innings_id', 'name', 'runs', 'balls', 'fours',
       'sixes', 'strike_rate', 'out_desc'],
      dtype='object')

In [16]:
df_players

,player_id,match_id,innings_id,name,runs,balls,fours,sixes,strike_rate,out_desc
0,18987,142142,1,Muhammad Waseem,0,1,0,0,0.00,lbw b Hemant Dhami
1,14999,142142,1,Adeeb Usmani,30,22,2,2,136.36,lbw b Sandeep Lamichhane
2,14227,142142,1,Alishan Sharafu,1,4,0,0,25.00,c Lokesh Bam b Nandan Yadav
3,6322,142142,1,Harpreet Singh Bhatia,1,3,0,0,33.33,lbw b Hemant Dhami
4,8351,142142,1,Akshdeep Nath,53,42,3,4,126.19,not out
5,1464054,142142,1,Sohaib Khan,0,5,0,0,0.00,c Hemant Dhami b Shahab Alam
6,22841,142142,1,Nilansh Keswani,0,2,0,0,0.00,run out (Dipendra Singh Airee/Lokesh Bam)
7,1448301,142142,1,Muhammad Arfan,32,36,2,1,88.89,c Dipendra Singh Airee b Sandeep Lamichhane
8,1447465,142142,1,Khuzaima Tanveer,0,1,0,0,0.00,c Dipendra Singh Airee b Sandeep Lamichhane
9,51658,142142,1,Muhammad Zuhaib,8,5,1,0,160.00,not out
10,1463374,142142,1,Ajay Kumar,0,0,0,0,0.00,not out
11,11290,142142,2,Kushal Bhurtel,84,57,12,2,147.37,not out
12,15400,142142,2,Kushal Malla,19,17,1,2,111.76,c Muhammad Waseem b Muhammad Arfan
13,1448017,142142,2,Santosh Yadav,1,4,0,0,25.00,run out (Adeeb Usmani)
14,11155,142142,2,Dipendra Singh Airee,23,17,3,0,135.29,not out
15,15397,142142,2,Lokesh Bam,0,0,0,0,0.00,not out
16,10126,142142,2,Aarif Sheikh,0,0,0,0,0.00,not out
17,20146,142142,2,Gulsan Jha,0,0,0,0,0.00,not out
18,12113,142142,2,Nandan Yadav,0,0,0,0,0.00,not out
19,11158,142142,2,Sandeep Lamichhane,0,0,0,0,0.00,not out
20,13222,142142,2,Shahab Alam,0,0,0,0,0.00,not out
21,52579,142142,2,Hemant Dhami,0,0,0,0,0.00,not out

In [17]:
df.drop_duplicates(inplace=True)
df_players.dropna(inplace=True)

In [18]:
def get_connection():
    return mysql.connector.connect(
        host="localhost",
        user="root",
        password="Abc@12345",
        database="cricket_db"
    )

In [19]:
conn = get_connection()
cur = conn.cursor()


cur.execute("""
CREATE TABLE IF NOT EXISTS matches (
    match_id BIGINT PRIMARY KEY,

    --  Series Info
    series_id BIGINT,
    series_name VARCHAR(255),

    --  Match Info
    match_desc VARCHAR(100),
    match_format VARCHAR(20),
    status TEXT,

    --  Teams
    team1 VARCHAR(100),
    team2 VARCHAR(100),

    --  Venue
    venue VARCHAR(100),
    city VARCHAR(100),

    --  Dates
    start_date DATETIME,
    end_date DATETIME,

    --  Optional Score Summary
    team1_runs INT,
    team2_runs INT
)
""")

In [20]:

# players table with FOREIGN KEY
cur.execute("""
CREATE TABLE IF NOT EXISTS players (
    player_id BIGINT,
    match_id BIGINT,
    name VARCHAR(100),
    runs INT,
    balls INT,
    fours INT,
    sixes INT,
    strike_rate FLOAT,
    out_desc TEXT,

    PRIMARY KEY (player_id, match_id),

    FOREIGN KEY (match_id) REFERENCES matches(match_id)
    ON DELETE CASCADE
)
""")

conn.commit()
cur.close()
conn.close()

In [21]:
def extract_matches(data):
    matches = []

    for type_match in data.get("typeMatches", []):
        for series in type_match.get("seriesMatches", []):
            wrapper = series.get("seriesAdWrapper", {})

            for match in wrapper.get("matches", []):
                info = match.get("matchInfo", {})
                score = match.get("matchScore", {})

                matches.append({
                    "match_id": info.get("matchId"),
                    "series_id": info.get("seriesId"),
                    "series_name": info.get("seriesName"),
                    "match_desc": info.get("matchDesc"),
                    "match_format": info.get("matchFormat"),
                    "status": info.get("status"),
                    "team1": info.get("team1", {}).get("teamName"),
                    "team2": info.get("team2", {}).get("teamName"),
                    "venue": info.get("venueInfo", {}).get("ground"),
                    "city": info.get("venueInfo", {}).get("city"),
                    "start_date": info.get("startDate"),
                    "end_date": info.get("endDate"),
                    "team1_runs": score.get("team1Score", {}).get("inngs1", {}).get("runs", 0),
                    "team2_runs": score.get("team2Score", {}).get("inngs1", {}).get("runs", 0)
                })

    return matches

In [22]:
def convert_dates(matches):
    for m in matches:
        m["start_date"] = pd.to_datetime(m["start_date"], unit='ms') if m["start_date"] else None
        m["end_date"] = pd.to_datetime(m["end_date"], unit='ms') if m["end_date"] else None
    return matches

In [23]:
def insert_matches(matches):
    conn = get_connection()
    cur = conn.cursor()

    query = """
    INSERT INTO matches (
        match_id, series_id, series_name, match_desc, match_format,
        status, team1, team2, venue, city,
        start_date, end_date, team1_runs, team2_runs
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON DUPLICATE KEY UPDATE 
        series_name=VALUES(series_name),
        match_desc=VALUES(match_desc),
        match_format=VALUES(match_format),
        status=VALUES(status),
        team1=VALUES(team1),
        team2=VALUES(team2),
        venue=VALUES(venue),
        city=VALUES(city),
        start_date=VALUES(start_date),
        end_date=VALUES(end_date),
        team1_runs=VALUES(team1_runs),
        team2_runs=VALUES(team2_runs)
    """

    values = []
    for m in matches:
        values.append((
            m.get("match_id"),
            m.get("series_id"),
            m.get("series_name"),
            m.get("match_desc"),
            m.get("match_format"),
            m.get("status"),
            m.get("team1"),
            m.get("team2"),
            m.get("venue"),
            m.get("city"),
            m.get("start_date"),
            m.get("end_date"),
            m.get("team1_runs") or 0,
            m.get("team2_runs") or 0
        ))

    cur.executemany(query, values)
    conn.commit()
    cur.close()
    conn.close()

In [24]:
def extract_players(scorecard, match_id):
    players = []

    for innings in scorecard.get("scorecard", []):
        for b in innings.get("batsman", []):
            players.append({
                "player_id": b.get("id"),
                "match_id": match_id,
                "name": b.get("name"),
                "runs": b.get("runs", 0),
                "balls": b.get("balls", 0),
                "fours": b.get("fours", 0),
                "sixes": b.get("sixes", 0),
                "strike_rate": float(b.get("strkrate", 0) or 0),
                "out_desc": b.get("outdec") or "not out"
            })

    return players

In [25]:
def insert_players(players):
    conn = get_connection()
    cur = conn.cursor()

    query = """
    INSERT INTO players 
    (player_id, match_id, name, runs, balls, fours, sixes, strike_rate, out_desc)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
    """

    values = []
    for p in players:
        values.append((
            p.get("player_id"),
            p.get("match_id"),
            p.get("name"),
            p.get("runs", 0),
            p.get("balls", 0),
            p.get("fours", 0),
            p.get("sixes", 0),
            p.get("strike_rate", 0),
            p.get("out_desc")
        ))

    cur.executemany(query, values)
    conn.commit()
    cur.close()
    conn.close()

In [26]:
matches = extract_matches(data)
matches = convert_dates(matches)

# insert matches first
insert_matches(matches)

# for each match → extract + insert players
for m in matches:
    match_id = m["match_id"]

    # ⚠️ here you must fetch scorecard API for each match
    players = extract_players(scorecard, match_id)

    insert_players(players)

C:\Users\hp\AppData\Local\Temp\ipykernel_20536\959014740.py:3: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  m["start_date"] = pd.to_datetime(m["start_date"], unit='ms') if m["start_date"] else None
C:\Users\hp\AppData\Local\Temp\ipykernel_20536\959014740.py:4: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  m["end_date"] = pd.to_datetime(m["end_date"], unit='ms') if m["end_date"] else None